apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
spec:
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo