apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: kibana
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: eshop-helm-repo
        namespace: flux-system
      interval: 5m
  targetNamespace: logging
  dependsOn:
    - name: elasticsearch
      namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Elasticsearch connection
    elasticsearchHosts: "http://elasticsearch-master.logging:9200"