apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  releaseName: kibana
  interval: 15m
  chart:
    spec:
      chart: kibana
      version: 8.*
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    elasticsearchHosts: "http://elasticsearch-master:9200"
    service:
      type: ClusterIP
