apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-infra
spec:
  interval: 10m
  releaseName: redis
  targetNamespace: storage
  chart:
    spec:
      chart: redis
      version: "20.13.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-infra
  values:
    architecture: standalone
    image:
      registry: docker.io
      repository: bitnami/redis
      tag: latest
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
