apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: rabbitmq
        namespace: flux-system
  install:
    createNamespace: true
  values:
    auth:
      username: user
      password: user123
    service:
      type: ClusterIP
