apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  releaseName: rabbitmq
  interval: 10m
  chart:
    spec:
      chart: rabbitmq
      version: "12.10.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      username: user
      password: user123
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 4.1.3-debian-12-r1
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
