apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  releaseName: rabbitmq
  interval: 10m
  chart:
    spec:
      chart: rabbitmq
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  timeout: 10m
  values:
    auth:
      username: user
      password: user123
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
