apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: flux-apps
spec:
  interval: 5m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.1"  # Latest stable as of 2025
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-apps
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      metrics:
        enabled: true
