apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zipkin
spec:
  chart:
    spec:
      chart: zipkin
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo