apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-base
spec:
  chart:
    spec:
      chart: helm/app-boilerplate-chart
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo