apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ .Values.releaseName | default "app-base" }}
spec:
  releaseName: {{ .Values.releaseName | default "app-base" }}
  chart:
    spec:
      chart: eshopmicroserviceacr.azurecr.io/helm/app-boilerplate-chart:1.0.2
      sourceRef:
        kind: HelmRepository
        name: eshop-acr
  values:
    image: 
      repository: "{{ .Values.image.repository }}"
      tag: "{{ .Values.image.tag }}"
      pullPolicy: "{{ .Values.image.pullPolicy }}"
    replicaCount: {{ .Values.replicaCount }}
    service: 
      type: {{ .Values.service.type }}
      port: {{ .Values.service.port }}
      containerPort: {{ .Values.service.containerPort }}
    configMapName: "{{ .Values.configMapName }}"
    secretName: "{{ .Values.secretName }}"
