apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-placeholder
  namespace: default
spec:
  releaseName: app-placeholder
  interval: 5m
  chart:
    spec:
      chart: app-boilerplate-chart
      sourceRef:
        kind: HelmRepository
        name: eshop-acr
        namespace: flux-system
      version: 1.0.2
  valuesFrom:
    - kind: ConfigMap
      name: app-placeholder-config
    - kind: Secret
      name: app-placeholder-secret
