apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-placeholder
  namespace: flux-apps
spec:
  releaseName: app-placeholder
  interval: 5m
  chart:
    spec:
      chart: app-boilerplate-chart
      sourceRef:
        kind: HelmRepository
        name: eshop-acr-repo
        namespace: flux-apps
      version: 1.0.3
  valuesFrom: []