apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-base
spec:
  chart:
    spec:
      chart: myapp-boilerplate
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo