apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-base
spec:
  chart:
    spec:
      chart: eshopmicroserviceacr.azurecr.io/helm/app-boilerplate-chart:0.1.0
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo