apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app-base
  namespace: eshopmicroservice
spec:
  interval: 5m
  releaseName: app-base
  chart:
    spec:
      chart: app-boilerplate-chart
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: eshop-acr
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: app-values
      valuesKey: values.yaml
