apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  labels:
    app: order-api
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
      version: blue
  template:
    metadata:
      labels:
        app: order-api
        version: blue
    spec:
      containers:
        - name: order-api
          image: myregistry.azurecr.io/order-api:v1.0.0
          envFrom:
            - configMapRef:
                name: orderapi-config
