apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.23.0"  # ✅ adjust to your Istio version
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  targetNamespace: istio-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      istioNamespace: istio-system
