apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: istiod
      version: "1.20.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
      namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    pilot:
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 4Gi
      autoscaleEnabled: true
      autoscaleMin: 2
      autoscaleMax: 5
    
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1Gi
      
      # Enable tracing
      tracer:
        zipkin:
          address: zipkin.tracing:9411
    
    # Telemetry for Prometheus
    telemetry:
      enabled: true