apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: "1.23.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 12h
  targetNamespace: istio-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultRevision: default