apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  
  install:
    remediation:
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
    # IMPORTANT: Force recreation for StatefulSets
    force: true
  
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.6.0-debian-12-r0"
      pullPolicy: IfNotPresent

    architecture: standalone

    auth:
      postgresPassword: postgres123
      enablePostgresUser: true

    primary:
      podSecurityContext:
        enabled: false
      
      containerSecurityContext:
        enabled: false
      
      persistence:
        enabled: false
      
      service:
        type: ClusterIP
      
      readinessProbe:
        enabled: true
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6
      
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 6

    volumePermissions:
      enabled: false

    metrics:
      enabled: false

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi