apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "16.2.0-debian-12-r0"  # Use specific version instead of 'latest'

    architecture: standalone

    auth:
      postgresPassword: postgres123

    primary:
      # Fix the security context - these settings work together
      podSecurityContext:
        enabled: true
        fsGroup: 1001
        fsGroupChangePolicy: "OnRootMismatch"  # Important for performance
      
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      
      # Use emptyDir with proper configuration
      persistence:
        enabled: true
        storageClass: ""  # Use default storage class or emptyDir
        size: 8Gi
        # If you want to use emptyDir (non-persistent, for testing):
        # existingClaim: ""
        # subPath: ""
      
      # Alternative: Force emptyDir
      extraVolumes:
        - name: data
          emptyDir: {}
      
      extraVolumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
      
      service:
        type: ClusterIP

    # Disable volumePermissions init container if it's causing issues
    volumePermissions:
      enabled: false

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi