apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: "15.6.0-debian-12-r0"  # Use PostgreSQL 15 (smaller image)
      pullPolicy: IfNotPresent

    architecture: standalone

    auth:
      postgresPassword: postgres123
      enablePostgresUser: true

    primary:
      podSecurityContext:
        enabled: false
      
      containerSecurityContext:
        enabled: false
      
      persistence:
        enabled: false
      
      service:
        type: ClusterIP

    volumePermissions:
      enabled: false

    metrics:
      enabled: false  # Disable metrics to reduce startup time

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi