apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: "15.2.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: latest

    architecture: standalone
    auth:
      postgresPassword: postgres123
    primary:
      persistence:
        enabled: true
      podSecurityContext:
        fsGroup: 1001
      containerSecurityContext:
        runAsUser: 1001
      service:
        type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
