apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: tracing
spec:
  releaseName: jaeger
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-infra
  values:
    allInOne:
      enabled: false  # disable all-in-one
    query:
      enabled: true
      service:
        type: ClusterIP  # required for Ingress
        port: 16686  # External port that we'll use
        targetPort: 16686  # Container port
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    collector:
      enabled: true
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    agent:
      enabled: false
      # service:
      #   type: ClusterIP
    storage:
      type: memory
