# FIXED infrastructure/apps/elasticsearch/helmrelease.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 10m
  timeout: 20m
  releaseName: elasticsearch
  
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 24h
  
  targetNamespace: logging
  
  install:
    crds: Skip
    createNamespace: true
    remediation:
      retries: 3
    timeout: 20m
  
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 20m
  
  values:
    replicas: 1
    minimumMasterNodes: 1
    
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=5s"
    
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    
    esJavaOpts: "-Xmx512m -Xms512m"
    
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "default"
      resources:
        requests:
          storage: 10Gi
    
    esConfig:
      elasticsearch.yml: |
        cluster.name: "elasticsearch"
        network.host: 0.0.0.0
        xpack.security.enabled: false
        discovery.type: single-node
    
    # THIS IS THE FIX! Enable the sysctl init container
    sysctlInitContainer:
      enabled: true
    
    # Adjust readiness probe
    readinessProbe:
      failureThreshold: 10
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 3
      timeoutSeconds: 10
    
    # Security context for init container
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000