apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 30m
  timeout: 20m
  releaseName: elasticsearch
  
  chart:
    spec:
      chart: elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 12h
  
  targetNamespace: logging
  
  install:
    createNamespace: false
    remediation:
      retries: 3
    timeout: 20m
  
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 20m
  
  values:
    # Cluster name
    clusterName: "elasticsearch"
    nodeGroup: "master"
    
    # Replicas - use 1 for dev, 3 for production
    replicas: 1
    minimumMasterNodes: 1
    
    # Image
    image: "docker.elastic.co/elasticsearch/elasticsearch"
    imageTag: "8.5.1"
    imagePullPolicy: "IfNotPresent"
    
    # Pod labels
    labels:
      app: elasticsearch
      component: logging
    
    # Resources
    resources:
      requests:
        cpu: "500m"
        memory: "2Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
    
    # JVM heap size (50% of memory limit)
    esJavaOpts: "-Xmx2g -Xms2g"
    
    # Extra environment variables
    extraEnvs:
      - name: ELASTIC_PASSWORD
        value: "changeme"  # Change this!
      - name: discovery.type
        value: "single-node"  # Change to "zen" for multi-node
    
    # Elasticsearch configuration
    esConfig:
      elasticsearch.yml: |
        # Cluster settings
        cluster.name: elasticsearch
        network.host: 0.0.0.0
        
        # Security settings (disabled for simplicity, enable in production!)
        xpack.security.enabled: false
        xpack.security.transport.ssl.enabled: false
        xpack.security.http.ssl.enabled: false
        
        # Monitoring
        xpack.monitoring.collection.enabled: true
        
        # Index management
        action.auto_create_index: true
        action.destructive_requires_name: true
    
    # Persistence
    persistence:
      enabled: true
      labels:
        enabled: false
    
    # Volume claim template
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "managed-premium"  # AKS storage class
      resources:
        requests:
          storage: 30Gi
    
    # Service
    service:
      enabled: true
      type: ClusterIP
      httpPort: 9200
      transportPort: 9300
      annotations: {}
      labels: {}
    
    # Ingress (disabled - using Istio)
    ingress:
      enabled: false
    
    # Network policy
    networkPolicy:
      enabled: false
    
    # Pod disruption budget
    maxUnavailable: 1
    
    # Update strategy
    updateStrategy: RollingUpdate
    
    # Anti-affinity
    antiAffinity: "soft"
    antiAffinityTopologyKey: "kubernetes.io/hostname"
    
    # Node selector
    nodeSelector: {}
    
    # Tolerations
    tolerations: []
    
    # Init containers
    sysctlInitContainer:
      enabled: true
    
    # Security context
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
    
    # Readiness probe
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 3
      timeoutSeconds: 5
    
    # Health check host
    clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
    
    # Lifecycle hooks
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 20"]
    
    # Extra init containers (increase vm.max_map_count)
    extraInitContainers:
      - name: increase-vm-max-map
        image: busybox:latest
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
    
    # Prometheus monitoring
    prometheus:
      enabled: false