apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: logging
spec:
  chart:
    spec:
      chart: elasticsearch
      version: 19.*
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 15m
  values:
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
