apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  releaseName: elasticsearch
  
  chart:
    spec:
      chart: elasticsearch
      version: "7.9.2"  # Stable, well-tested version
      sourceRef:
        kind: HelmRepository
        name: elastic-helm-repo
        namespace: flux-system
      interval: 24h
  
  install:
    crds: Skip
    createNamespace: false
    remediation:
      retries: 5
    timeout: 30m
  
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      retries: 5
    timeout: 15m
  
  # Keep minimal values for reliability
  values:
    # Single node setup
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    
    # Small heap
    esJavaOpts: "-Xmx256m -Xms256m"
    
    # Disable resource-intensive features
    sysctlInitContainer:
      enabled: false
    
    # Service
    service:
      type: ClusterIP
    