apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: elasticsearch
      version: "7.9.2"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    image:
      repository: docker.elastic.co/elasticsearch/elasticsearch
      tag: "7.9.2"
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
