apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: flux
spec:
  interval: 30m
  timeout: 10m
  releaseName: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      version: "8.9.x"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 12h
  targetNamespace: logging
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicas: 1
    persistence:
      enabled: true
      storageClassName: managed-premium
      size: 20Gi
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
