apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 10m
  timeout: 15m
  releaseName: elasticsearch
  
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"  # Stable, well-tested version
      sourceRef:
        kind: HelmRepository
        name: elastic-helm-repo
        namespace: flux-system
      interval: 24h
  
  install:
    crds: Skip
    createNamespace: false
    remediation:
      retries: 5
    timeout: 15m
  
  upgrade:
    crds: Skip
    cleanupOnFail: true
    remediation:
      retries: 5
    timeout: 15m
  
  # Keep minimal values for reliability
  values:
    # Single node setup
    replicas: 1
    minimumMasterNodes: 1
    
    # Reduced resources for stability
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    
    # Smaller heap
    esJavaOpts: "-Xmx512m -Xms512m"
    
    # Storage
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "default"  # Use default storage class
      resources:
        requests:
          storage: 10Gi
    
    # Minimal ES config
    esConfig:
      elasticsearch.yml: |
        cluster.name: "elasticsearch"
        network.host: 0.0.0.0
        xpack.security.enabled: false
        discovery.type: single-node
    
    # Service
    service:
      type: ClusterIP
    
    # Disable features we don't need
    sysctlInitContainer:
      enabled: false
    
    # Simple probes
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 3
      timeoutSeconds: 5