apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  releaseName: kibana
  interval: 15m
  targetNamespace: elasticsearch
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-infra
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"
    ingress:
      enabled: false
      # annotations:
      #   kubernetes.io/ingress.class: nginx
      # hosts:
      #   - host: kibana.flux-system.example.com
      #     paths:
      #       - path: /
      #         pathType: Prefix
