apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-infra
spec:
  releaseName: kibana
  interval: 15m
  targetNamespace: logging
  chart:
    spec:
      chart: kibana
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-infra
  install:
    createNamespace: true
    timeout: 15m  # Install timeout
    remediation:
      retries: 5  # Retry up to 5 times
  upgrade:
    timeout: 15m  # Upgrade timeout
    remediation:
      retries: 5
      remediateLastFailure: true  # Retry even after failure
  values:
    elasticsearchHosts: "http://elasticsearch-master:9200"
    ingress:
      enabled: false

    replicas: 1
    
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    # Critical: Adjust health checks for slow Kibana startup
    healthCheckPath: "/app/kibana"
    
    readinessProbe:
      initialDelaySeconds: 90  # Wait longer before first check
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 30  # Allow many failures during startup
      successThreshold: 1
    
    livenessProbe:
      initialDelaySeconds: 180  # Wait 3 minutes before checking
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 3
      successThreshold: 1