apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-infra
spec:
  interval: 10m
  releaseName: rabbitmq
  targetNamespace: messaging   # <- Deploy into separate namespace
  chart:
    spec:
      chart: rabbitmq
      version: "16.0.14"       # <- Use a valid chart version
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-infra
  values:
    auth:
      username: user
      password: password123
      erlangCookie: secretcookie
    service:
      type: ClusterIP
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
