apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: flux-infra
spec:
  interval: 10m
  timeout: 10m
  releaseName: rabbitmq
  targetNamespace: messaging  # Deploy to messaging namespace
  chart:
    spec:
      chart: rabbitmq
      version: "14.6.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-infra
      interval: 10m
  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    force: true
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: bitnami/rabbitmq
      tag: 3.13.7-debian-12-r5
      pullPolicy: IfNotPresent
    
    auth:
      username: user
      password: password123
      erlangCookie: secretcookie123456789012
    
    replicaCount: 1
    
    clustering:
      enabled: false
    
    persistence:
      enabled: false
    
    resources:
      limits:
        cpu: 300m
        memory: 384Mi
      requests:
        cpu: 100m
        memory: 256Mi
    
    service:
      type: ClusterIP
      ports:
        amqp: 5672
        manager: 15672
    
    livenessProbe:
      enabled: true
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 20
      failureThreshold: 6
    
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 20
      failureThreshold: 3
    
    extraPlugins: "rabbitmq_management"