apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 10m
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: "1.21.0"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istio-base
      kind: HelmRelease
  values:
    # Minimal control plane configuration - tune for production
    global:
      proxy:
        autoInject: enabled
    pilot:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
