apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-infra
spec:
  releaseName: elasticsearch
  interval: 15m
  targetNamespace: elasticsearch
  chart:
    spec:
      chart: elasticsearch
      version: "7.17.3"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-infra
  values:
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
