apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: basket-dev
  namespace: flux-apps
spec:
  interval: 5m
  path: ./apps/basket/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: basket
  dependsOn:
    - name: flux-apps