apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipkin
  namespace: flux-system
spec:
  releaseName: zipkin
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: zipkin
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: openzipkin
        namespace: flux-system
  values:
    image:
      repository: openzipkin/zipkin
      tag: 2.24
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    service:
      type: ClusterIP
