apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipkin
  namespace: flux-system
spec:
  interval: 10m
  releaseName: zipkin
  chart:
    spec:
      chart: zipkin
      version: "0.4.0"   
      sourceRef:
        kind: HelmRepository
        name: zipkin
        namespace: flux-system
  install:
    createNamespace: true
  values: 
    replicaCount: 1
    persistence:
      enabled: false
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: zipkin.flux-system.example.com
          paths:
            - path: /
              pathType: Prefix
