apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zipkin
  namespace: flux-system
spec:
  releaseName: zipkin
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: zipkin
      version: "0.3.3"   # or another version supported in that repo
      sourceRef:
        kind: HelmRepository
        name: zipkin-helm
        namespace: flux-system
  values:
    image:
      repository: openzipkin/zipkin
      tag: 2.24
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
    service:
      type: ClusterIP
