apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.11.2"  # ✅ Valid version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: LoadBalancer   # Exposes the ingress to public IP
      watchIngressWithoutClass: true
      ingressClassResource:
        name: nginx
        controllerValue: "k8s.io/ingress-nginx"
