apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: flux-system
spec:
  releaseName: jaeger
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    allInOne:
      enabled: false  # disable all-in-one
    query:
      enabled: true
      service:
        type: ClusterIP  # required for Ingress
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    collector:
      enabled: true
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    agent:
      enabled: true
      service:
        type: ClusterIP
    storage:
      type: memory
