apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  releaseName: jaeger
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    allInOne:
      enabled: false  # disable all-in-one
    query:
      enabled: true
      service:
        type: ClusterIP
    collector:
      enabled: true
      service:
        type: ClusterIP
    agent:
      enabled: true
      service:
        type: ClusterIP
    storage:
      type: memory
