apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  releaseName: jaeger
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    allInOne:
      enabled: true
      image:
        repository: jaegertracing/all-in-one
        tag: "1.53"
      service:
        type: ClusterIP
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: jaeger.flux-system.example.com
            paths:
              - path: /
                pathType: Prefix
    storage:
      type: memory
