apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  interval: 5m
  releaseName: jaeger
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      retries: 3
  values:
    allInOne:
      enabled: true
      image:
        repository: jaegertracing/all-in-one
        tag: "1.53"
      ingress:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      service:
        type: ClusterIP
        ports:
          - name: query-ui
            port: 16686
            targetPort: 16686
            protocol: TCP
          - name: admin
            port: 16687
            targetPort: 16687
            protocol: TCP
          - name: agent-compact
            port: 6831
            targetPort: 6831
            protocol: UDP
    storage:
      type: memory