apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 10m
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: "jaeger-3.4.1"                       # choose a stable chart version
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # For small clusters use "allInOne: true" - for production disable and use separate components
    allInOne: false
    provisionDataStore: true
    persistence:
      # enable persistence for collector/query if you have PVs/StorageClass
      enabled: true
      size: 10Gi
    cassandra:                              # or use "es" (elasticsearch) depending on storage
      enabled: false
    esIndexCleaner:
      enabled: false
    collector:
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    query:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "300m"
          memory: "512Mi"
    ingress:
      enabled: true
      # If you use an ingress controller, configure ingress annotations/hosts here
      annotations: {}
      hosts:
        - host: jaeger.monitoring.example.com
          paths:
            - path: /
              pathType: Prefix
