apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 10m
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: "3.4.1"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
      interval: 5m
  targetNamespace: tracing
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: elasticsearch         # ensure Elasticsearch is deployed first
      namespace: flux-system
  values:
    allInOne:
      enabled: false
    provisionDataStore:           # fixed structure
      cassandra: false
      elasticsearch: true
    storage:
      type: elasticsearch
      options:
        es:
          server-urls: http://elasticsearch-master.logging.svc.cluster.local:9200
    collector:
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    query:
      service:
        type: LoadBalancer
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "300m"
          memory: "512Mi"
    ingress:
      enabled: false
