apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 15m
  releaseName: jaeger
  chart:
    spec:
      chart: jaeger
      version: 3.*
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  install:
    timeout: 10m
    remediation:
      retries: 3
  values:
    storage:
      type: memory           
    provisionDataStore:
      cassandra: false
      elasticsearch: false
    allInOne:
      enabled: true          
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    agent:
      enabled: false         
    collector:
      enabled: false
    query:
      enabled: false
    service:
      type: ClusterIP
