apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: flux-system
spec:
  releaseName: jaeger
  interval: 15m
  chart:
    spec:
      chart: jaeger
      version: 3.4.1
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    allInOne:
      enabled: true
      service:
        type: ClusterIP
        queryPort: 16686
      image:
        repository: jaegertracing/all-in-one
        tag: "1.53"
    storage:
      type: memory
